server:
  port: 8000
  servlet:
    #    设置响应的字符编码
    encoding:
      charset: utf-8
      force: true
      enabled: true
spring:
  application:
    name: RAGTranslationApplication

ai:
  embeddingStore:
    qdrant:
      collectionName: ragTranslation-1226
      host: 192.168.179.130
      port: 6334


