server:
  port: 8080
  servlet:
    #    设置响应的字符编码
    encoding:
      charset: utf-8
      force: true
      enabled: true
spring:
  application:
    name: RAGTranslationApplication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://192.168.179.130:3306/guiguxiaozhi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ai:
  embeddingStore:
    qdrant:
      collectionName: ragTranslation-1226
      host: 192.168.179.130
      port: 6334


