server:
  port: 8080
  servlet:
    #    设置响应的字符编码
    encoding:
      charset: utf-8
      force: true
      enabled: true
    context-parameters:
      # 防止长时间请求挂起
      tomcat-servlet:
        async-supported: true
  tomcat:
    connection-timeout: 150000    # 60秒连接超时

spring:
  application:
    name: RAGTranslationApplication
  web:
    timeout: 150s                 # Web请求超时
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://192.168.179.130:3306/guiguxiaozhi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ai:
  dashscope:
    apiKey: ${DASHSCOPE_API_KEY}
    model: qwen3-235b-a22b
    base-url: https://dashscope.aliyuncs.com/compatible-mode/v1

  embeddingStore:
    qdrant:
      collectionName: ragTranslation-1226
      host: 192.168.179.130
      port: 6334

  ollama:
    base-url: http://localhost:11434
    model: deepseek-r1:8b
    options:
      temperature: 0.7


